version: "3.9"

services:
  db:
    container_name: postgres_nirs
    restart: always
    build:
      dockerfile: build/postgres.Dockerfile
    volumes:
      - type: volume
        source: postgresdb-data
        target: /var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - ${DB_PORT}:5432
    networks:
      - nirs-network
  main:
    depends_on:
      - db
    container_name: mainNIRS
    build:
      dockerfile: build/main.Dockerfile
    ports:
      - '8100:8100'
    env_file:
      - .env
    networks:
      - nirs-network
  fill_db:
    depends_on:
      - db
    container_name: fillerDB
    build:
      dockerfile: build/filldb.Dockerfile
    ports:
      - '8101:8101'
    env_file:
      - .env
    networks:
      - nirs-network

volumes:
  postgresdb-data:
    driver: local

networks:
  nirs-network:
    name: nirs-network
    driver: bridge